apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-api-deployment
  labels:
    app: sentiment-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
        - name: sentiment-api
          image: final-project:v1
          imagePullPolicy: Never   # use local image loaded into Minikube
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_DIR
              value: "/app/artifacts/model_v2"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
